
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: kryptoPetshop_development

test:
  <<: *default
  database: db/kryptoPetshop_test

production:
  <<: *default
  database: db/kryptoPetshop_production
