
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: postgres
  password: root

development:
  <<: *default
  database: kryptoPetshop_development

test:
  <<: *default
  database: kryptoPetshop_test

production:
  <<: *default
  database: kryptoPetshop_production
